services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      SSH_HOST: "${SSH_HOST}"
      SSH_USER: "${SSH_USER}"
      LOCAL_PORT: "${LOCAL_PORT}"
      REMOTE_PORT: "${REMOTE_PORT}"
    ports:
      - "3000:80"
      - "1935:1935"
